--
-- PostgreSQL database dump
--

\restrict wy44rd8NKpE0VI2S5Kwujb7QLbbg31QQiWIeyiNp5NdZlGJl0OZdPj7vR1414yP

-- Dumped from database version 16.12 (9893e46)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: payments_feecollectioncheckoutsession; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_feecollectioncheckoutsession (
    id bigint NOT NULL,
    provider_order_id character varying(120) NOT NULL,
    amount_inr numeric(12,2) NOT NULL,
    amount_paise integer NOT NULL,
    collection_mode character varying(20) NOT NULL,
    payload jsonb NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    school_id bigint NOT NULL,
    CONSTRAINT payments_feecollectioncheckoutsession_amount_paise_check CHECK ((amount_paise >= 0))
);


--
-- Name: payments_feecollectioncheckoutsession_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_feecollectioncheckoutsession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_feecollectioncheckoutsession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_parentpaymentintent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_parentpaymentintent (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    currency character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    provider character varying(30) NOT NULL,
    provider_order_id character varying(120) NOT NULL,
    paid_at timestamp with time zone,
    notes text NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    school_id bigint NOT NULL,
    student_id bigint,
    student_fee_id bigint
);


--
-- Name: payments_parentpaymentintent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_parentpaymentintent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_parentpaymentintent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_parentpaymenttransaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_parentpaymenttransaction (
    id bigint NOT NULL,
    provider character varying(30) NOT NULL,
    provider_payment_id character varying(120) NOT NULL,
    provider_signature character varying(255) NOT NULL,
    amount numeric(12,2) NOT NULL,
    currency character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    raw_payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    intent_id bigint NOT NULL
);


--
-- Name: payments_parentpaymenttransaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_parentpaymenttransaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_parentpaymenttransaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_platforminvoice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_platforminvoice (
    id bigint NOT NULL,
    billing_cycle character varying(20) NOT NULL,
    amount numeric(12,2) NOT NULL,
    currency character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    period_start date,
    period_end date,
    due_date date,
    paid_at timestamp with time zone,
    notes jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: payments_platforminvoice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_platforminvoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_platforminvoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_platformpaymenttransaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_platformpaymenttransaction (
    id bigint NOT NULL,
    provider character varying(30) NOT NULL,
    provider_order_id character varying(120) NOT NULL,
    provider_payment_id character varying(120) NOT NULL,
    provider_signature character varying(255) NOT NULL,
    amount numeric(12,2) NOT NULL,
    currency character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    raw_payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    invoice_id bigint NOT NULL
);


--
-- Name: payments_platformpaymenttransaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_platformpaymenttransaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_platformpaymenttransaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_schoolpaymentconfig; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_schoolpaymentconfig (
    id bigint NOT NULL,
    platform_billing_cycle character varying(20) NOT NULL,
    razorpay_route_account_id character varying(100) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: payments_schoolpaymentconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_schoolpaymentconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_schoolpaymentconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_budget; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_budget (
    id bigint NOT NULL,
    academic_year character varying(20) NOT NULL,
    planned_amount numeric(12,2) NOT NULL,
    alert_threshold_percentage integer NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: schools_budget_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_budget ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_budget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_expense; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_expense (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    amount numeric(12,2) NOT NULL,
    date date NOT NULL,
    payment_mode character varying(20) NOT NULL,
    reference_number character varying(100) NOT NULL,
    receipt character varying(100),
    tags character varying(500) NOT NULL,
    is_recurring boolean NOT NULL,
    recurring_interval character varying(20) NOT NULL,
    recurring_end_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    category_id bigint,
    school_id bigint NOT NULL,
    vendor_id bigint
);


--
-- Name: schools_expense_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_expense ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_expense_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_expensecategory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_expensecategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    color character varying(7) NOT NULL,
    icon character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: schools_expensecategory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_expensecategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_expensecategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_feepayment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_feepayment (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    discount numeric(10,2) NOT NULL,
    payment_date date NOT NULL,
    payment_mode character varying(50) NOT NULL,
    transaction_id character varying(100) NOT NULL,
    receipt_number character varying(50) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    student_fee_id bigint NOT NULL
);


--
-- Name: schools_feepayment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_feepayment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_feepayment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_feestructure; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_feestructure (
    id bigint NOT NULL,
    class_name character varying(50) NOT NULL,
    amount numeric(10,2) NOT NULL,
    due_day integer NOT NULL,
    late_fine_per_day numeric(10,2) NOT NULL,
    academic_year character varying(20) NOT NULL,
    allow_yearly_payment boolean NOT NULL,
    yearly_discount_percent numeric(5,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    fee_type_id bigint NOT NULL,
    school_id bigint NOT NULL,
    school_class_id bigint
);


--
-- Name: schools_feestructure_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_feestructure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_feestructure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_feetype; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_feetype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    is_system boolean NOT NULL,
    description character varying(255) NOT NULL,
    billing_period character varying(20) NOT NULL,
    school_id bigint
);


--
-- Name: schools_feetype_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_feetype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_feetype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_school; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_school (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    address text NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(50) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    logo character varying(100),
    plan character varying(20) NOT NULL,
    max_students integer NOT NULL,
    max_staff_logins integer NOT NULL,
    academic_year_start_month integer NOT NULL,
    trial_ends_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    fee_start_day integer NOT NULL
);


--
-- Name: schools_school_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_school ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_school_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_schoolclass; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_schoolclass (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: schools_schoolclass_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_schoolclass ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_schoolclass_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_section; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_section (
    id bigint NOT NULL,
    name character varying(20) NOT NULL,
    display_order integer NOT NULL,
    school_class_id bigint NOT NULL
);


--
-- Name: schools_section_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_section ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_student; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_student (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    class_name character varying(50) NOT NULL,
    section_legacy character varying(10) NOT NULL,
    parent_name character varying(200) NOT NULL,
    parent_phone character varying(20) NOT NULL,
    parent_email character varying(254) NOT NULL,
    admission_number character varying(50) NOT NULL,
    roll_number character varying(50) NOT NULL,
    admission_date date,
    charges_effective_from date,
    uses_transport boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL,
    school_class_id bigint,
    section_id bigint
);


--
-- Name: schools_student_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_studentfee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_studentfee (
    id bigint NOT NULL,
    month integer NOT NULL,
    year integer NOT NULL,
    amount numeric(10,2) NOT NULL,
    late_fine numeric(10,2) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    due_date date,
    created_at timestamp with time zone NOT NULL,
    fee_structure_id bigint NOT NULL,
    student_id bigint NOT NULL
);


--
-- Name: schools_studentfee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_studentfee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_studentfee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_studentfeestructurechoice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_studentfeestructurechoice (
    id bigint NOT NULL,
    effective_from date,
    created_at timestamp with time zone NOT NULL,
    fee_structure_id bigint NOT NULL,
    student_id bigint NOT NULL
);


--
-- Name: schools_studentfeestructurechoice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_studentfeestructurechoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_studentfeestructurechoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_subscription (
    id bigint NOT NULL,
    plan character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    razorpay_subscription_id character varying(100) NOT NULL,
    razorpay_customer_id character varying(100) NOT NULL,
    current_period_start date,
    current_period_end date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: schools_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    phone character varying(20) NOT NULL,
    school_id bigint
);


--
-- Name: schools_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: schools_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: schools_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools_vendor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools_vendor (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    contact_person character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    address text NOT NULL,
    gst_number character varying(50) NOT NULL,
    pan_number character varying(20) NOT NULL,
    payment_terms character varying(200) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: schools_vendor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools_vendor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_vendor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: payments_feecollectioncheckoutsession payments_feecollectioncheckoutsession_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_feecollectioncheckoutsession
    ADD CONSTRAINT payments_feecollectioncheckoutsession_pkey PRIMARY KEY (id);


--
-- Name: payments_feecollectioncheckoutsession payments_feecollectioncheckoutsession_provider_order_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_feecollectioncheckoutsession
    ADD CONSTRAINT payments_feecollectioncheckoutsession_provider_order_id_key UNIQUE (provider_order_id);


--
-- Name: payments_parentpaymentintent payments_parentpaymentintent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_parentpaymentintent
    ADD CONSTRAINT payments_parentpaymentintent_pkey PRIMARY KEY (id);


--
-- Name: payments_parentpaymenttransaction payments_parentpaymenttransaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_parentpaymenttransaction
    ADD CONSTRAINT payments_parentpaymenttransaction_pkey PRIMARY KEY (id);


--
-- Name: payments_platforminvoice payments_platforminvoice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_platforminvoice
    ADD CONSTRAINT payments_platforminvoice_pkey PRIMARY KEY (id);


--
-- Name: payments_platformpaymenttransaction payments_platformpaymenttransaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_platformpaymenttransaction
    ADD CONSTRAINT payments_platformpaymenttransaction_pkey PRIMARY KEY (id);


--
-- Name: payments_schoolpaymentconfig payments_schoolpaymentconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_schoolpaymentconfig
    ADD CONSTRAINT payments_schoolpaymentconfig_pkey PRIMARY KEY (id);


--
-- Name: payments_schoolpaymentconfig payments_schoolpaymentconfig_school_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_schoolpaymentconfig
    ADD CONSTRAINT payments_schoolpaymentconfig_school_id_key UNIQUE (school_id);


--
-- Name: schools_budget schools_budget_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_budget
    ADD CONSTRAINT schools_budget_pkey PRIMARY KEY (id);


--
-- Name: schools_budget schools_budget_school_id_category_id_ac_2a0ddf46_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_budget
    ADD CONSTRAINT schools_budget_school_id_category_id_ac_2a0ddf46_uniq UNIQUE (school_id, category_id, academic_year);


--
-- Name: schools_expense schools_expense_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_expense
    ADD CONSTRAINT schools_expense_pkey PRIMARY KEY (id);


--
-- Name: schools_expensecategory schools_expensecategory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_expensecategory
    ADD CONSTRAINT schools_expensecategory_pkey PRIMARY KEY (id);


--
-- Name: schools_expensecategory schools_expensecategory_school_id_name_e7f28847_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_expensecategory
    ADD CONSTRAINT schools_expensecategory_school_id_name_e7f28847_uniq UNIQUE (school_id, name);


--
-- Name: schools_feepayment schools_feepayment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feepayment
    ADD CONSTRAINT schools_feepayment_pkey PRIMARY KEY (id);


--
-- Name: schools_feestructure schools_feestructure_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feestructure
    ADD CONSTRAINT schools_feestructure_pkey PRIMARY KEY (id);


--
-- Name: schools_feestructure schools_feestructure_school_id_fee_type_id_sc_72ccb6f8_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feestructure
    ADD CONSTRAINT schools_feestructure_school_id_fee_type_id_sc_72ccb6f8_uniq UNIQUE (school_id, fee_type_id, school_class_id, academic_year);


--
-- Name: schools_feetype schools_feetype_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feetype
    ADD CONSTRAINT schools_feetype_pkey PRIMARY KEY (id);


--
-- Name: schools_school schools_school_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_school
    ADD CONSTRAINT schools_school_pkey PRIMARY KEY (id);


--
-- Name: schools_schoolclass schools_schoolclass_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_schoolclass
    ADD CONSTRAINT schools_schoolclass_pkey PRIMARY KEY (id);


--
-- Name: schools_schoolclass schools_schoolclass_school_id_name_42f7b95e_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_schoolclass
    ADD CONSTRAINT schools_schoolclass_school_id_name_42f7b95e_uniq UNIQUE (school_id, name);


--
-- Name: schools_section schools_section_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_section
    ADD CONSTRAINT schools_section_pkey PRIMARY KEY (id);


--
-- Name: schools_section schools_section_school_class_id_name_95af14bd_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_section
    ADD CONSTRAINT schools_section_school_class_id_name_95af14bd_uniq UNIQUE (school_class_id, name);


--
-- Name: schools_student schools_student_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_student
    ADD CONSTRAINT schools_student_pkey PRIMARY KEY (id);


--
-- Name: schools_studentfee schools_studentfee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_studentfee
    ADD CONSTRAINT schools_studentfee_pkey PRIMARY KEY (id);


--
-- Name: schools_studentfee schools_studentfee_student_id_fee_structure_40c032ba_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_studentfee
    ADD CONSTRAINT schools_studentfee_student_id_fee_structure_40c032ba_uniq UNIQUE (student_id, fee_structure_id, month, year);


--
-- Name: schools_studentfeestructurechoice schools_studentfeestruct_student_id_fee_structure_c2598207_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_studentfeestructurechoice
    ADD CONSTRAINT schools_studentfeestruct_student_id_fee_structure_c2598207_uniq UNIQUE (student_id, fee_structure_id);


--
-- Name: schools_studentfeestructurechoice schools_studentfeestructurechoice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_studentfeestructurechoice
    ADD CONSTRAINT schools_studentfeestructurechoice_pkey PRIMARY KEY (id);


--
-- Name: schools_subscription schools_subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_subscription
    ADD CONSTRAINT schools_subscription_pkey PRIMARY KEY (id);


--
-- Name: schools_subscription schools_subscription_school_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_subscription
    ADD CONSTRAINT schools_subscription_school_id_key UNIQUE (school_id);


--
-- Name: schools_user_groups schools_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user_groups
    ADD CONSTRAINT schools_user_groups_pkey PRIMARY KEY (id);


--
-- Name: schools_user_groups schools_user_groups_user_id_group_id_b90ce8e4_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user_groups
    ADD CONSTRAINT schools_user_groups_user_id_group_id_b90ce8e4_uniq UNIQUE (user_id, group_id);


--
-- Name: schools_user schools_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user
    ADD CONSTRAINT schools_user_pkey PRIMARY KEY (id);


--
-- Name: schools_user_user_permissions schools_user_user_permis_user_id_permission_id_c52cce07_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user_user_permissions
    ADD CONSTRAINT schools_user_user_permis_user_id_permission_id_c52cce07_uniq UNIQUE (user_id, permission_id);


--
-- Name: schools_user_user_permissions schools_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user_user_permissions
    ADD CONSTRAINT schools_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: schools_user schools_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user
    ADD CONSTRAINT schools_user_username_key UNIQUE (username);


--
-- Name: schools_vendor schools_vendor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_vendor
    ADD CONSTRAINT schools_vendor_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: payments_feecollectionch_provider_order_id_912efecc_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_feecollectionch_provider_order_id_912efecc_like ON public.payments_feecollectioncheckoutsession USING btree (provider_order_id varchar_pattern_ops);


--
-- Name: payments_feecollectioncheckoutsession_created_by_id_4b68c425; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_feecollectioncheckoutsession_created_by_id_4b68c425 ON public.payments_feecollectioncheckoutsession USING btree (created_by_id);


--
-- Name: payments_feecollectioncheckoutsession_school_id_17efb4bf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_feecollectioncheckoutsession_school_id_17efb4bf ON public.payments_feecollectioncheckoutsession USING btree (school_id);


--
-- Name: payments_parentpaymentintent_created_by_id_d55ed7bc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_parentpaymentintent_created_by_id_d55ed7bc ON public.payments_parentpaymentintent USING btree (created_by_id);


--
-- Name: payments_parentpaymentintent_school_id_d9a8554a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_parentpaymentintent_school_id_d9a8554a ON public.payments_parentpaymentintent USING btree (school_id);


--
-- Name: payments_parentpaymentintent_student_fee_id_2cd775ef; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_parentpaymentintent_student_fee_id_2cd775ef ON public.payments_parentpaymentintent USING btree (student_fee_id);


--
-- Name: payments_parentpaymentintent_student_id_a95904e8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_parentpaymentintent_student_id_a95904e8 ON public.payments_parentpaymentintent USING btree (student_id);


--
-- Name: payments_parentpaymenttransaction_intent_id_a810e667; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_parentpaymenttransaction_intent_id_a810e667 ON public.payments_parentpaymenttransaction USING btree (intent_id);


--
-- Name: payments_platforminvoice_school_id_5a79bf0b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_platforminvoice_school_id_5a79bf0b ON public.payments_platforminvoice USING btree (school_id);


--
-- Name: payments_platformpaymenttransaction_invoice_id_8c88ef8f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_platformpaymenttransaction_invoice_id_8c88ef8f ON public.payments_platformpaymenttransaction USING btree (invoice_id);


--
-- Name: schools_budget_category_id_5dedd70e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_budget_category_id_5dedd70e ON public.schools_budget USING btree (category_id);


--
-- Name: schools_budget_school_id_af889e6c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_budget_school_id_af889e6c ON public.schools_budget USING btree (school_id);


--
-- Name: schools_expense_category_id_f7b860c8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_expense_category_id_f7b860c8 ON public.schools_expense USING btree (category_id);


--
-- Name: schools_expense_created_by_id_f67ddd76; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_expense_created_by_id_f67ddd76 ON public.schools_expense USING btree (created_by_id);


--
-- Name: schools_expense_school_id_3ca9f8a0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_expense_school_id_3ca9f8a0 ON public.schools_expense USING btree (school_id);


--
-- Name: schools_expense_vendor_id_b850495c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_expense_vendor_id_b850495c ON public.schools_expense USING btree (vendor_id);


--
-- Name: schools_expensecategory_school_id_272c8376; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_expensecategory_school_id_272c8376 ON public.schools_expensecategory USING btree (school_id);


--
-- Name: schools_feepayment_created_by_id_f521d48b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_feepayment_created_by_id_f521d48b ON public.schools_feepayment USING btree (created_by_id);


--
-- Name: schools_feepayment_student_fee_id_a361af6b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_feepayment_student_fee_id_a361af6b ON public.schools_feepayment USING btree (student_fee_id);


--
-- Name: schools_feestructure_fee_type_id_95ce7b4f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_feestructure_fee_type_id_95ce7b4f ON public.schools_feestructure USING btree (fee_type_id);


--
-- Name: schools_feestructure_school_class_id_887ad50d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_feestructure_school_class_id_887ad50d ON public.schools_feestructure USING btree (school_class_id);


--
-- Name: schools_feestructure_school_id_0eff42d6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_feestructure_school_id_0eff42d6 ON public.schools_feestructure USING btree (school_id);


--
-- Name: schools_feetype_school_id_9179a869; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_feetype_school_id_9179a869 ON public.schools_feetype USING btree (school_id);


--
-- Name: schools_schoolclass_school_id_6c98e06b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_schoolclass_school_id_6c98e06b ON public.schools_schoolclass USING btree (school_id);


--
-- Name: schools_section_school_class_id_2732815a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_section_school_class_id_2732815a ON public.schools_section USING btree (school_class_id);


--
-- Name: schools_student_school_class_id_8232952b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_student_school_class_id_8232952b ON public.schools_student USING btree (school_class_id);


--
-- Name: schools_student_school_id_56d739ce; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_student_school_id_56d739ce ON public.schools_student USING btree (school_id);


--
-- Name: schools_student_section_id_f2cffb06; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_student_section_id_f2cffb06 ON public.schools_student USING btree (section_id);


--
-- Name: schools_studentfee_fee_structure_id_9311ea2b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_studentfee_fee_structure_id_9311ea2b ON public.schools_studentfee USING btree (fee_structure_id);


--
-- Name: schools_studentfee_student_id_2e89da05; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_studentfee_student_id_2e89da05 ON public.schools_studentfee USING btree (student_id);


--
-- Name: schools_studentfeestructurechoice_fee_structure_id_c91620c9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_studentfeestructurechoice_fee_structure_id_c91620c9 ON public.schools_studentfeestructurechoice USING btree (fee_structure_id);


--
-- Name: schools_studentfeestructurechoice_student_id_9d359cf0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_studentfeestructurechoice_student_id_9d359cf0 ON public.schools_studentfeestructurechoice USING btree (student_id);


--
-- Name: schools_user_groups_group_id_0d424c63; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_user_groups_group_id_0d424c63 ON public.schools_user_groups USING btree (group_id);


--
-- Name: schools_user_groups_user_id_ed4342c5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_user_groups_user_id_ed4342c5 ON public.schools_user_groups USING btree (user_id);


--
-- Name: schools_user_school_id_e8f9d470; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_user_school_id_e8f9d470 ON public.schools_user USING btree (school_id);


--
-- Name: schools_user_user_permissions_permission_id_c10c123f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_user_user_permissions_permission_id_c10c123f ON public.schools_user_user_permissions USING btree (permission_id);


--
-- Name: schools_user_user_permissions_user_id_8d17e178; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_user_user_permissions_user_id_8d17e178 ON public.schools_user_user_permissions USING btree (user_id);


--
-- Name: schools_user_username_7b960f38_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_user_username_7b960f38_like ON public.schools_user USING btree (username varchar_pattern_ops);


--
-- Name: schools_vendor_school_id_ff93c1c4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schools_vendor_school_id_ff93c1c4 ON public.schools_vendor USING btree (school_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_schools_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_schools_user_id FOREIGN KEY (user_id) REFERENCES public.schools_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_feecollectioncheckoutsession payments_feecollecti_created_by_id_4b68c425_fk_schools_u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_feecollectioncheckoutsession
    ADD CONSTRAINT payments_feecollecti_created_by_id_4b68c425_fk_schools_u FOREIGN KEY (created_by_id) REFERENCES public.schools_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_feecollectioncheckoutsession payments_feecollecti_school_id_17efb4bf_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_feecollectioncheckoutsession
    ADD CONSTRAINT payments_feecollecti_school_id_17efb4bf_fk_schools_s FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_parentpaymentintent payments_parentpayme_created_by_id_d55ed7bc_fk_schools_u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_parentpaymentintent
    ADD CONSTRAINT payments_parentpayme_created_by_id_d55ed7bc_fk_schools_u FOREIGN KEY (created_by_id) REFERENCES public.schools_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_parentpaymenttransaction payments_parentpayme_intent_id_a810e667_fk_payments_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_parentpaymenttransaction
    ADD CONSTRAINT payments_parentpayme_intent_id_a810e667_fk_payments_ FOREIGN KEY (intent_id) REFERENCES public.payments_parentpaymentintent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_parentpaymentintent payments_parentpayme_school_id_d9a8554a_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_parentpaymentintent
    ADD CONSTRAINT payments_parentpayme_school_id_d9a8554a_fk_schools_s FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_parentpaymentintent payments_parentpayme_student_fee_id_2cd775ef_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_parentpaymentintent
    ADD CONSTRAINT payments_parentpayme_student_fee_id_2cd775ef_fk_schools_s FOREIGN KEY (student_fee_id) REFERENCES public.schools_studentfee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_parentpaymentintent payments_parentpayme_student_id_a95904e8_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_parentpaymentintent
    ADD CONSTRAINT payments_parentpayme_student_id_a95904e8_fk_schools_s FOREIGN KEY (student_id) REFERENCES public.schools_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_platforminvoice payments_platforminv_school_id_5a79bf0b_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_platforminvoice
    ADD CONSTRAINT payments_platforminv_school_id_5a79bf0b_fk_schools_s FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_platformpaymenttransaction payments_platformpay_invoice_id_8c88ef8f_fk_payments_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_platformpaymenttransaction
    ADD CONSTRAINT payments_platformpay_invoice_id_8c88ef8f_fk_payments_ FOREIGN KEY (invoice_id) REFERENCES public.payments_platforminvoice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_schoolpaymentconfig payments_schoolpayme_school_id_bfba1c34_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_schoolpaymentconfig
    ADD CONSTRAINT payments_schoolpayme_school_id_bfba1c34_fk_schools_s FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_budget schools_budget_category_id_5dedd70e_fk_schools_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_budget
    ADD CONSTRAINT schools_budget_category_id_5dedd70e_fk_schools_e FOREIGN KEY (category_id) REFERENCES public.schools_expensecategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_budget schools_budget_school_id_af889e6c_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_budget
    ADD CONSTRAINT schools_budget_school_id_af889e6c_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_expense schools_expense_category_id_f7b860c8_fk_schools_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_expense
    ADD CONSTRAINT schools_expense_category_id_f7b860c8_fk_schools_e FOREIGN KEY (category_id) REFERENCES public.schools_expensecategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_expense schools_expense_created_by_id_f67ddd76_fk_schools_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_expense
    ADD CONSTRAINT schools_expense_created_by_id_f67ddd76_fk_schools_user_id FOREIGN KEY (created_by_id) REFERENCES public.schools_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_expense schools_expense_school_id_3ca9f8a0_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_expense
    ADD CONSTRAINT schools_expense_school_id_3ca9f8a0_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_expense schools_expense_vendor_id_b850495c_fk_schools_vendor_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_expense
    ADD CONSTRAINT schools_expense_vendor_id_b850495c_fk_schools_vendor_id FOREIGN KEY (vendor_id) REFERENCES public.schools_vendor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_expensecategory schools_expensecategory_school_id_272c8376_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_expensecategory
    ADD CONSTRAINT schools_expensecategory_school_id_272c8376_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_feepayment schools_feepayment_created_by_id_f521d48b_fk_schools_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feepayment
    ADD CONSTRAINT schools_feepayment_created_by_id_f521d48b_fk_schools_user_id FOREIGN KEY (created_by_id) REFERENCES public.schools_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_feepayment schools_feepayment_student_fee_id_a361af6b_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feepayment
    ADD CONSTRAINT schools_feepayment_student_fee_id_a361af6b_fk_schools_s FOREIGN KEY (student_fee_id) REFERENCES public.schools_studentfee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_feestructure schools_feestructure_fee_type_id_95ce7b4f_fk_schools_feetype_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feestructure
    ADD CONSTRAINT schools_feestructure_fee_type_id_95ce7b4f_fk_schools_feetype_id FOREIGN KEY (fee_type_id) REFERENCES public.schools_feetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_feestructure schools_feestructure_school_class_id_887ad50d_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feestructure
    ADD CONSTRAINT schools_feestructure_school_class_id_887ad50d_fk_schools_s FOREIGN KEY (school_class_id) REFERENCES public.schools_schoolclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_feestructure schools_feestructure_school_id_0eff42d6_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feestructure
    ADD CONSTRAINT schools_feestructure_school_id_0eff42d6_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_feetype schools_feetype_school_id_9179a869_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_feetype
    ADD CONSTRAINT schools_feetype_school_id_9179a869_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_schoolclass schools_schoolclass_school_id_6c98e06b_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_schoolclass
    ADD CONSTRAINT schools_schoolclass_school_id_6c98e06b_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_section schools_section_school_class_id_2732815a_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_section
    ADD CONSTRAINT schools_section_school_class_id_2732815a_fk_schools_s FOREIGN KEY (school_class_id) REFERENCES public.schools_schoolclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_student schools_student_school_class_id_8232952b_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_student
    ADD CONSTRAINT schools_student_school_class_id_8232952b_fk_schools_s FOREIGN KEY (school_class_id) REFERENCES public.schools_schoolclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_student schools_student_school_id_56d739ce_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_student
    ADD CONSTRAINT schools_student_school_id_56d739ce_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_student schools_student_section_id_f2cffb06_fk_schools_section_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_student
    ADD CONSTRAINT schools_student_section_id_f2cffb06_fk_schools_section_id FOREIGN KEY (section_id) REFERENCES public.schools_section(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_studentfee schools_studentfee_fee_structure_id_9311ea2b_fk_schools_f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_studentfee
    ADD CONSTRAINT schools_studentfee_fee_structure_id_9311ea2b_fk_schools_f FOREIGN KEY (fee_structure_id) REFERENCES public.schools_feestructure(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_studentfee schools_studentfee_student_id_2e89da05_fk_schools_student_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_studentfee
    ADD CONSTRAINT schools_studentfee_student_id_2e89da05_fk_schools_student_id FOREIGN KEY (student_id) REFERENCES public.schools_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_studentfeestructurechoice schools_studentfeest_fee_structure_id_c91620c9_fk_schools_f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_studentfeestructurechoice
    ADD CONSTRAINT schools_studentfeest_fee_structure_id_c91620c9_fk_schools_f FOREIGN KEY (fee_structure_id) REFERENCES public.schools_feestructure(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_studentfeestructurechoice schools_studentfeest_student_id_9d359cf0_fk_schools_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_studentfeestructurechoice
    ADD CONSTRAINT schools_studentfeest_student_id_9d359cf0_fk_schools_s FOREIGN KEY (student_id) REFERENCES public.schools_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_subscription schools_subscription_school_id_561dcc45_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_subscription
    ADD CONSTRAINT schools_subscription_school_id_561dcc45_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_user_groups schools_user_groups_group_id_0d424c63_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user_groups
    ADD CONSTRAINT schools_user_groups_group_id_0d424c63_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_user_groups schools_user_groups_user_id_ed4342c5_fk_schools_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user_groups
    ADD CONSTRAINT schools_user_groups_user_id_ed4342c5_fk_schools_user_id FOREIGN KEY (user_id) REFERENCES public.schools_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_user schools_user_school_id_e8f9d470_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user
    ADD CONSTRAINT schools_user_school_id_e8f9d470_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_user_user_permissions schools_user_user_pe_permission_id_c10c123f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user_user_permissions
    ADD CONSTRAINT schools_user_user_pe_permission_id_c10c123f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_user_user_permissions schools_user_user_pe_user_id_8d17e178_fk_schools_u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_user_user_permissions
    ADD CONSTRAINT schools_user_user_pe_user_id_8d17e178_fk_schools_u FOREIGN KEY (user_id) REFERENCES public.schools_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schools_vendor schools_vendor_school_id_ff93c1c4_fk_schools_school_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools_vendor
    ADD CONSTRAINT schools_vendor_school_id_ff93c1c4_fk_schools_school_id FOREIGN KEY (school_id) REFERENCES public.schools_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict wy44rd8NKpE0VI2S5Kwujb7QLbbg31QQiWIeyiNp5NdZlGJl0OZdPj7vR1414yP

