# Generated by Django 6.0.2 on 2026-02-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_increase_phone_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['school_class', 'fee_type']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['school_class', 'name']},
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'fee_type', 'school_class', 'academic_year')},
        ),
    ]
