# Generated by Django 6.0.2 on 2026-02-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_protect_class_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['school_class', 'section', 'name']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='section',
            new_name='section_legacy',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.schoolclass')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.section'),
        ),
    ]
