# Generated by Django 6.0.2 on 2026-02-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_add_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uses_transport',
            field=models.BooleanField(default=True),
        ),
    ]
