# Generated by Django 6.0.4 on 2026-05-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_user_module_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Per-module access for staff: view, create, edit, delete, actions.'),
        ),
    ]
