# Generated by Django 6.0.2 on 2026-02-28 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_add_academic_year_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount given on this payment (amount credited = amount, cash received = amount - discount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='allow_yearly_payment',
            field=models.BooleanField(default=True, help_text='Parents can pay whole year at once'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='yearly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % when paying full year upfront', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
