# Generated by Django 6.0.2 on 2026-03-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_add_yearly_payment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='charges_effective_from',
            field=models.DateField(blank=True, help_text='Date from which monthly fees apply. Can be future. If not set, admission_date is used.', null=True),
        ),
    ]
