# Generated by Django 6.0.4 on 2026-06-13 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_parent_role'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='schools_pho_school__1ec8c8_idx',
            old_name='schools_pho_school__a8e2b4_idx',
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('enroll_student', 'Student enrollment'), ('parent_register', 'Parent registration'), ('parent_reset_password', 'Parent password reset')], default='enroll_student', max_length=32),
        ),
        migrations.AlterField(
            model_name='school',
            name='fee_start_day',
            field=models.IntegerField(default=1, help_text='School billing day (1–28): used when adding students to decide if the join month is billed.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
