# Generated by Django 6.0.4 on 2026-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_remove_feetype_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='billing_period',
        ),
        migrations.AddField(
            model_name='feetype',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly'), ('one_time', 'One-Time Payment')], default='monthly', max_length=20),
        ),
    ]
