# Generated by Django 6.0.4 on 2026-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_phone_otp_parent_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='plan_period_end',
            field=models.DateField(blank=True, help_text='Last day of the current paid subscription period.', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_blocked',
            field=models.BooleanField(default=False, help_text='When true, dashboard access is limited until the owner renews or downgrades usage.'),
        ),
    ]
