# Generated by Django 6.0.4 on 2026-06-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolreceiptsettings',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Uploaded signature image shown on printed receipts.', null=True, upload_to='receipt_signatures/'),
        ),
    ]
