# Generated by Django 6.0.4 on 2026-06-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_whatsapp_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('both', 'SMS + WhatsApp'), ('class_groups', 'Class WhatsApp groups only')], default='both', max_length=16),
        ),
    ]
